export const englishTexts = {
  'page.title': 'TeaCeremony',
  'room.unavailable': 'The room is resting. Come back a little later.',

  'hand.sip': 'Sip',

  'debug.title': 'Debug',
  'debug.camera': 'Camera',
  'debug.camera.room': 'Room view',
  'debug.camera.firstPerson': 'First person',
  'debug.controls': 'First-person controls',
  'debug.controls.twoSticks': 'Two sticks',
  'debug.controls.mouseAndKeyboard': 'Mouse and keyboard',
  'debug.controls.mouseAndWalkStick': 'Mouse and a walk stick',
  'debug.controls.keyboardAndLookStick': 'Keyboard and a look stick',
  'debug.sticks': 'Sticks',
  'debug.sticks.walkOnTheLeft': 'Walk left, look right',
  'debug.sticks.lookOnTheLeft': 'Look left, walk right',
  'debug.close': 'Close',

  'aim.tiltButton': '🫖',
  'aim.hint': 'Drag to move what you pour from. Hold 🫖 with another finger to tilt it. Tap anywhere to stop.',

  'sip.noTea.1': 'Hmm… no smell of tea in here at all.',
  'sip.noTea.2': 'Just water. The leaves never met it.',
  'sip.noTea.3': 'Clear as the tap. Tea was meant to happen here.',
  'sip.noTea.4': 'Water, honest and plain. The tea is still in the caddy.',
  'sip.tooHot.1': 'Mm, a touch too hot. Give it a moment.',
  'sip.tooHot.2': 'Hot on the lips. A few breaths and it will be lovely.',
  'sip.tooHot.3': 'Still a little fierce. Almost there.',
  'sip.tooHot.4': 'Ooh, hot. I rushed that one.',
  'sip.amongLeaves.1': 'Tea with a side of leaves. I am chewing my ceremony.',
  'sip.amongLeaves.2': 'The kettle is sulking over there. It thought we were friends.',
  'sip.amongLeaves.3': 'A leaf is stuck to my lip. Very rustic. Very wet.',
  'sip.overbrewed.1': 'Oof… it has gone bitter. It steeped too long.',
  'sip.overbrewed.2': 'That bites back. Too long with the leaves.',
  'sip.overbrewed.3': 'Dark and harsh. The leaves forgot to leave.',
  'sip.overbrewed.4': 'Bitter all the way down. Too long in the kettle.',
  'sip.extremelyStrong.1': 'I can hear colours now. Is that part of the ceremony?',
  'sip.extremelyStrong.2': 'A spoon would stand up in this. Respect.',
  'sip.extremelyStrong.3': 'Only a true lover of strong tea survives this. I think I did.',
  'sip.bitter.1': 'A bitter edge. A little less time next pour.',
  'sip.bitter.2': 'A touch sharp at the end.',
  'sip.bitter.3': 'Good, then a bitter whisper.',
  'sip.bitter.4': 'Almost. A shade too long.',
  'sip.tooStrong.1': 'Strong… it grips the tongue.',
  'sip.tooStrong.2': 'Heavy. Fewer leaves next time.',
  'sip.tooStrong.3': 'That wakes you up. Maybe too much.',
  'sip.tooStrong.4': 'Thick as a winter coat.',
  'sip.cold.1': 'Cold already. The moment has passed.',
  'sip.cold.2': 'It waited too long for me.',
  'sip.cold.3': 'Cold tea, quiet regret.',
  'sip.cold.4': 'The warmth has gone somewhere else.',
  'sip.weak.1': 'Pale and thin. It wanted more leaves, or more time.',
  'sip.weak.2': 'Shy tea. Barely there.',
  'sip.weak.3': 'Mostly water, a rumour of tea.',
  'sip.weak.4': 'Gentle… too gentle.',
  'sip.rich.1': 'Rich and deep. Lovely.',
  'sip.rich.2': 'Full and round. Oh, that is good.',
  'sip.rich.3': 'Deep as the evening, and just as calm.',
  'sip.rich.4': 'Rich enough to lean on.',
  'sip.coolingButGood.1': 'Good, though it is cooling.',
  'sip.coolingButGood.2': 'Still good. Drink it before it goes.',
  'sip.coolingButGood.3': 'Nice, a little shy of warm.',
  'sip.coolingButGood.4': 'Cooler now, but still lovely.',
  'sip.justRight.1': 'Ahh… just right.',
  'sip.justRight.2': 'Mm. Exactly this.',
  'sip.justRight.3': 'That is the one.',
  'sip.justRight.4': 'Warm, clear, kind. I could sit with this all day.',

  'spill.1': 'Oops… some for the table.',
  'spill.2': 'The table wanted a sip too.',
  'spill.3': "Oh no, a puddle. Where's the cloth?",
  'spill.4': 'Well, that went everywhere.',

  'sillIsTheRoomsOwn.1': 'Wow, you tap everything here. The room would like to keep something for itself.',
  'sillIsTheRoomsOwn.2': 'The figurines on the windowsill belong to the room. Admire them from here.',
  'sillIsTheRoomsOwn.3': 'You have touched almost everything in this house. These two are off the list.',
  'sillIsTheRoomsOwn.4': 'Not these ones. Some things in a house are only for looking at.',

  'bowlKeptOffTheHeater.1': 'Have you lost your mind? That bowl is the dearest thing in this house. Put your own hand there instead.',
  'bowlKeptOffTheHeater.2': 'The Guild of Beautiful Bowls has received a complaint about us. It is not amused.',
  'bowlKeptOffTheHeater.3': 'A potter shaped this bowl five centuries ago. They would never forgive us.',
  'bowlKeptOffTheHeater.4': 'A bowl on a hot plate? The bowl says no. I say no. Even the plate looks worried.',

  'caddyKeptOffTheHeater.1': 'If these were coffee beans, maybe. This tea was roasted long ago and is ready to drink. Shoo.',
  'caddyKeptOffTheHeater.2': 'The leaves are dry enough, thank you. Nobody ordered tea toast.',
  'caddyKeptOffTheHeater.3': 'Charcoal is not a tea. These leaves would like to stay leaves.',
  'caddyKeptOffTheHeater.4': 'The caddy has lived a quiet life on the shelf. It does not need a sauna.',
  'caddyWashedOut.1': 'Lovely. And what exactly are we drinking now? The view?',
  'caddyWashedOut.2': 'The next tea delivery is a week away. Enjoy your hot water until then.',
  'caddyWashedOut.3': 'Oh, I see. Off you go to your coffee, then.',
  'caddyWashedOut.4': 'All of it, down the drain. Is tea some kind of joke to you?',
  'visit.welcomeBack': 'The room waited for you. The tea may not have.',
  'visit.continue': 'Continue',
  'visit.startOver': 'Start over',
  'visit.startOverNote': 'Your achievements will most likely stay, and the rest are still yours to earn. The world you know may change a little.',
  'visit.lostToAnUpdate': 'The house was rebuilt while you were away. Your last visit did not survive the renovation.',
  'spoonReturned.1': 'The spoon is back in its old place. Bamboo grows fast, apparently.',
  'spoonReturned.2': 'There is a spoon again. It knows nothing about the last one, and let us keep it that way.',
  'spoonReturned.3': 'Someone swept up the ash and left a new spoon in its place. I will not ask who.',
  'spoonReturned.4': 'A new spoon is waiting where the old one lay. Let us not introduce it to the heater.',
  'emptyCaddyRefilled.1': 'Fresh leaves in the caddy. Try to drink these ones.',
  'emptyCaddyRefilled.2': 'The caddy is full again. Will the leaves make it to the kettle this time?',
  'emptyCaddyRefilled.3': 'Someone filled the caddy while we were away.',
  'emptyCaddyRefilled.4': 'The delivery came early. The caddy is full, and the sink is not invited.',
  'spoonAndCaddyReturned.1': 'A new spoon and a full caddy. Let us try not to burn one or rinse the other.',
  'spoonAndCaddyReturned.2': 'The spoon is back and the caddy is full. The house forgives more than it should.',
  'spoonAndCaddyReturned.3': 'Fresh leaves, a fresh spoon. Everything is ready for you to ruin it again.',
  'spoonAndCaddyReturned.4': 'While we were away, the spoon grew back and the caddy filled up. I have questions, but I will keep them to myself.',
  'youDied.title': 'YOU DIED',
  'youDied.restart': 'Start over',
  'lastWords.1': 'Tell the kettle… it was not its fault.',
  'lastWords.2': 'The whole caddy… at once… worth it.',
  'lastWords.3': 'Too strong. Tell the caddy I forgive it.',
  'obituary.1': 'Here lies a tea lover who brewed the whole caddy at once and drank it straight from the tin. Survived by ten tea bowls and a thermos.',
  'obituary.2': 'In loving memory. Cherished by the dragon and the toad, undone by a single caddy of tea.',
  'obituary.3': 'Gone today, strong to the end, like their tea. In lieu of flowers, please send a smaller caddy.',
  'obituary.4': 'Here rests one who wanted a stronger cup. They got one.',
  'handsFull.1': 'A third arm would help right now. Evolution is taking its time.',
  'handsFull.2': 'Telekinesis is still on my list. Put something down first.',
  'handsFull.3': 'Sorry, hands full. Unless you want me to carry it in my teeth.',
  'handsFullOfBowls.1': 'Waiters carry four bowls in one hand. I should practise that some quiet evening.',
  'handsFullOfBowls.2': 'Two bowls, two hands. Stacking them in one hand is a skill for another day.',
  'handsFullOfBowls.3': 'One day I will balance three bowls on one palm. Today is not that day.',
  'handsFullOfBowls.4': 'A real tea master holds two bowls in one hand. I will train when no one is watching.',
  'heaterTester.1': 'Everything goes on the heater, I see. Looks like we have caught ourselves a tester.',
  'heaterTester.2': "Mummy's little arsonist is at it again.",
  'heaterTester.3': 'Is this really what you came to this game for? I may have to report some worrying behaviour.',
  'heaterTester.4': 'Who would have thought this would become the most popular feature of the tea room.',
  'heaterTester.5': 'This is exactly the behaviour I expected from you.',
  'heaterTester.6': 'We are renaming ourselves Fire Room. Or The Fireplace. Send in your suggestions.',
  'everythingOnTheShelf.1': 'Everything on the shelf. This house has never been so tidy.',
  'everythingOnTheShelf.2': 'Every last thing put away. Is this a hobby, or should I be a little worried?',
  'everythingOnTheShelf.3': 'All on the shelf. Are you quite sure they are in the right order?',
  'everythingOnTheShelf.4': 'Very neat. Had it been up to me, I would have arranged it all quite differently.',

  'burntClothWashed.1': "Amazing. A burnt cloth washes back to new. I think I'll stay in this world.",
  'burntClothWashed.2': 'Not a trace of the fire. This world forgives things. I could live here.',
  'burntClothWashed.3': "Magic sink! The burn is gone. I'm never leaving.",
  'burntClothWashed.4': 'Burnt, rinsed, reborn. What a kind little world.',
  'smoulderingClothTaken.1': 'Careful with that. I never did get round to insuring this house.',
  'smoulderingClothTaken.2': 'We have only just moved in. Let us keep the walls a little longer.',
  'smoulderingClothTaken.3': 'Lovely. The last mortgage payment went out yesterday, and now this.',
  'smoulderingClothTaken.4': 'Sure, let it burn. We will just buy another house, as we always do.',
  'spoonCrumbled.1': 'And there goes our only spoon. No spoon, no leaves. Hot water it is, then.',
  'spoonCrumbled.2': 'Ash. That was bamboo a minute ago. Lovely trick. Now make it come back.',
  'spoonCrumbled.3': 'Well, that settles the tea for today. Unless you work out how to brew without a spoon. There might be a way.',
  'spoonCrumbled.4': 'Poor little spoon. It scooped so faithfully, and now it is a pinch of ash. 😭',
  'tooHotToHold.1': 'And then what? Juggle a glowing thermos?',
  'tooHotToHold.2': "Blister my palm and ruin a lovely day? I'll pass, thanks.",
  'tooHotToHold.3': "It's literally glowing. Even the thermos is telling you no.",

  'tapRanLong.1': '{litres} litres straight down the drain. The river sends its thanks.',
  'tapRanLong.2': 'That was {litres} litres for the sink. It has never been this hydrated.',

  'heaterRanLong.1': 'That much electricity would have bought a whole tin of good tea. Ah well, the air is warm.',
  'heaterRanLong.2': 'Promise me you do this before we leave the house, too.',
  'heaterRanLong.3': '{kilowattHours} kWh to warm the air. The power plant sends its warmest regards.',

  'settings.title': 'Settings',
  'settings.coatColour': 'Body colour',
  'settings.face': 'Face',
  'settings.face.nose': '1',
  'settings.face.eyes': '2',
  'settings.face.ears': '3',
  'settings.face.afro': '4',
  'settings.temperature': 'Temperature',
  'settings.nerdMode': 'Nerd mode',
  'settings.nerdModeNote': 'A thermostat on the heater and a thermometer on the kettle.',
  'settings.unit.celsius': '°C',
  'settings.unit.fahrenheit': '°F',
  'settings.advanced': 'Advanced',
  'settings.softShadowsInCorners': 'Soft shadows in corners',
  'settings.softShadowsInCornersWarning': 'Makes the room look deeper, but the game may start to lag on some phones.',
  'settings.glow': 'Glow of lamps',
  'settings.glowWarning': 'Lamps shine softly into the room around them, but the game may start to lag on some phones.',
  'settings.showFrameRate': 'Show frame rate',
  'settings.statistics': 'Statistics',
  'settings.timePlayed': 'Time in the tea room',
  'settings.timePlayed.underAMinute': 'less than a minute',
  'settings.timePlayed.minutes': '{minutes} min',
  'settings.timePlayed.hoursAndMinutes': '{hours} h {minutes} min',
  'settings.close': 'Close',
  'frameRate.reading': '{framesPerSecond} fps',
  'fullScreen.enter': 'Full screen',
  'fullScreen.leave': 'Leave full screen',
  'wall.prophecy.firstLine': 'The prophecy shall come true: one day a cherry pie will finish',
  'wall.prophecy.secondLine': 'this tea room, and it will live a life of its own. Or not.',
  'achievements.title': 'Achievements',
  'achievements.reset': 'Reset',
  'achievements.resetAgain': 'Tap again to reset',
  'achievements.close': 'Close',
  'achievement.unlocked': '🏅 {title}',
  'achievement.burntClothWashed.title': 'Phoenix',
  'achievement.burntClothWashed.done': 'Set the cloth on fire, then washed it back to new.',
  'achievement.spoonBurnt.title': 'Yeah, fuck me',
  'achievement.spoonBurnt.done': 'Burnt the spoon until it crumbled to ash in your hand.',
  'achievement.bowlTriedOnTheHeater.title': 'History Lesson',
  'achievement.bowlTriedOnTheHeater.done': 'Tried to put a tea bowl on the heater and heard why not.',
  'achievement.everythingOnTheShelf.title': 'DVD',
  'achievement.everythingOnTheShelf.done': 'Everything fit on the shelf. Perfectly. Not one thing left over.',
  'achievement.tableWiped.title': 'OCD',
  'achievement.tableWiped.done': 'Wiped two different puddles with the cloth.',
  'achievement.thermosGlowing.title': 'Hanami',
  'achievement.thermosGlowing.done': 'Sat by the heater and watched the thermos blossom red-hot.',
  'achievement.heaterTester.title': 'Hopeless',
  'achievement.heaterTester.done': 'Tried four or five different things on the working heater.',
  'achievement.roseBushTappedTenTimes.title': 'The Shawshank Redemption',
  'achievement.roseBushTappedTenTimes.done': 'Tapped the rose bush ten times in a row.',
  'achievement.perfectTea.title': 'Sommelier',
  'achievement.perfectTea.done': 'Brewed a bowl of tea that was just right.',
  'achievement.teaBrewedInTheBowl.title': 'Enlightened',
  'achievement.teaBrewedInTheBowl.done': 'Skipped the kettle, brewed the leaves right in a tea bowl and drank it.',
  'achievement.visitContinued.title': 'The Usual, Please',
  'achievement.visitContinued.done': 'Came back and continued a visit.',
  'achievement.tapAndHeaterLeftOn.title': "Parents Wouldn't Approve",
  'achievement.tapAndHeaterLeftOn.done': 'Ran the tap into an empty sink for two minutes and the heater without the kettle for two minutes, then turned both off.',
  'achievement.kettleBoiledDry.title': 'Patience of a Monk',
  'achievement.kettleBoiledDry.done': 'Filled the kettle to the brim, poured nothing from it, and waited on the heater until it boiled dry.',
  'achievement.shiva.title': 'Shiva',
  'achievement.died.title': "You know, I'm something of an enthusiast myself",
  'achievement.died.done': 'Your little heart could not take a brew that strong.',
  'achievement.delphicOracle.title': 'Delphic Oracle',
  'achievement.delphicOracle.done': 'Found the prophecy where nobody looks, and read it whole.',
  'achievement.shiva.done': 'Wanted a third arm so badly that you tapped one into being. So proud of you.',

  'offering.glow': '{figurine} glows softly.',
  'offering.subtle': '{figurine} seems pleased.',
  'offering.barely': '{figurine} barely notices.',
  'figurine.dragon': 'The dragon',
  'figurine.toad': 'The toad',
} as const
