type Lines = readonly [string, ...string[]]

export const englishTexts = {
  'page.title': 'TeaCeremony',
  'room.unavailable': 'The room is resting. Come back a little later.',

  'hand.sip': 'Sip',

  'debug.title': 'Debug',
  'debug.height': 'Height',
  'debug.height.value': '{centimetres} cm',
  'debug.height.lower': 'Shorter',
  'debug.height.higher': 'Taller',
  'debug.frameBudget': 'Show the frame budget',
  'debug.googlyEyes': 'Experimental eyes',
  'debug.giantAfro': 'Experimental hair',
  'debug.everyFaceAtOnce': 'Every face at once',
  'debug.fillTheKettle': 'Fill the kettle with boiling water',
  'debug.close': 'Close',
  'frameBudget.frame': '{framesPerSecond} fps, frame {average} ms, longest {longest} ms',
  'frameBudget.phase': '{phase} {milliseconds} ms',
  'frameBudget.drawing': '{drawCalls} draw calls, {triangles} triangles',
  'frameBudget.memory': '{geometries} geometries, {textures} textures, {programs} shaders',
  'frameBudget.counts': '{objects} scene objects, {elements} page elements',
  'frameBudget.phase.input': 'input',
  'frameBudget.phase.walking': 'walking',
  'frameBudget.phase.roomPlay': 'room play',
  'frameBudget.phase.simulation': 'simulation',
  'frameBudget.phase.bookkeeping': 'bookkeeping',
  'frameBudget.phase.camera': 'camera',
  'frameBudget.phase.carriedItems': 'carried items',
  'frameBudget.phase.roomParts': 'room parts',
  'frameBudget.phase.screenControls': 'screen controls',
  'frameBudget.phase.roomPass': 'room pass',
  'frameBudget.phase.glowPass': 'glow pass',
  'frameBudget.phase.heldItemsPass': 'held items pass',
  'frameBudget.phase.inspectionPass': 'inspection pass',
  'frameBudget.phase.smoothingPass': 'smoothing pass',

  'aim.tiltButton': 'Tilt to pour',
  'aim.whyButton': 'Why am I pouring?',
  'aim.why': 'You are pouring because you tapped the opening of a vessel while another vessel was chosen in your hand. Drag to move it, hold the pour button to tilt it, and tap anywhere else to stop.',
  'aim.hint': 'Drag to move what you pour from. Hold the pour button with another finger to tilt it. Tap anywhere to stop.',

  'visit.welcomeBack': 'The room waited for you. The tea may not have.',
  'visit.continue': 'Continue',
  'visit.startOver': 'Start over',
  'visit.startOverNote': 'Your achievements will most likely stay, and the rest are still yours to earn. The world you know may change a little.',
  'visit.startOverNoteWithoutAchievements': 'The world you know may change a little.',
  'visit.keys.title': 'Keys',
  'visit.keys.hands.key': '1  2',
  'visit.keys.hands': 'Choose a hand',
  'visit.keys.look.key': 'Hold 1  2',
  'visit.keys.look': 'Look closely at what the hand holds',
  'visit.keys.sip.key': 'E',
  'visit.keys.sip': 'Sip',
  'visit.keys.pour.key': 'Space',
  'visit.keys.pour': 'Tilt to pour',
  'visit.keys.walk.key': 'W A S D  or  ← ↑ ↓ →',
  'visit.keys.walk': 'Walk, in first person',
  'visit.keys.mouse.key': 'Esc',
  'visit.keys.mouse': 'Free the mouse, in first person',
  'visit.lostToAnUpdate': 'The house was rebuilt while you were away. Your last visit did not survive the renovation.',
  'youDied.title': 'YOU DIED',
  'youDied.restart': 'Start over',

  'settings.title': 'Settings',
  'settings.showAchievements': 'Show achievements',
  'settings.coatColour': 'Body colour',
  'settings.face': 'Face',
  'settings.face.nose': '1',
  'settings.face.eyes': '2',
  'settings.face.ears': '3',
  'settings.face.afro': '4',
  'settings.temperature': 'Temperature',
  'settings.nerdMode': 'Nerd mode',
  'settings.nerdModeNote': 'A thermostat on the heater and a thermometer on the kettle.',
  'settings.unit.celsius': '°C',
  'settings.unit.fahrenheit': '°F',
  'settings.advanced': 'Advanced',
  'settings.softShadowsInCorners': 'Soft shadows in corners',
  'settings.softShadowsInCornersWarning': 'Makes the room look deeper, but the game may start to lag on some phones.',
  'settings.glow': 'Glow of lamps',
  'settings.glowWarning': 'Lamps shine softly into the room around them, but the game may start to lag on some phones.',
  'settings.fullResolution': 'Full screen resolution',
  'settings.fullResolutionWarning': 'Sharpness: draws every pixel of the screen, so edges look crisper, but the game may start to lag on some phones.',
  'settings.smoothEdges': 'Smooth edges',
  'settings.smoothEdgesWarning': 'Softens the steps along edges, but blurs the picture a little, and the game may start to lag on some phones.',
  'settings.objectDetail': 'Object detail',
  'settings.objectDetail.full': 'Full',
  'settings.objectDetail.reduced': 'Reduced',
  'settings.objectDetailNote': 'Reduced draws faraway bowls and flowers a little simpler, so the phone stays cool. Up close, everything is always in full.',
  'settings.showFrameRate': 'Show frame rate',
  'settings.camera': 'Camera',
  'settings.camera.room': 'Room view',
  'settings.camera.firstPerson': 'First person',
  'settings.firstPersonNote': 'First person is new and not well tested yet.',
  'settings.controls': 'First-person controls',
  'settings.controls.twoSticks': 'Two sticks',
  'settings.controls.mouseAndKeyboard': 'Mouse and keyboard',
  'settings.controls.mouseAndWalkStick': 'Mouse and a walk stick',
  'settings.controls.keyboardAndLookStick': 'Keyboard and a look stick',
  'settings.sticks': 'Sticks',
  'settings.sticks.walkOnTheLeft': 'Walk left, look right',
  'settings.sticks.lookOnTheLeft': 'Look left, walk right',
  'settings.statistics': 'Statistics',
  'settings.timePlayed': 'Time in the tea room',
  'settings.timePlayed.underAMinute': 'less than a minute',
  'settings.timePlayed.minutes': '{minutes} min',
  'settings.timePlayed.hoursAndMinutes': '{hours} h {minutes} min',
  'settings.close': 'Close',
  'frameRate.reading': '{framesPerSecond} fps',
  'fullScreen.enter': 'Full screen',
  'fullScreen.leave': 'Leave full screen',
  'firstPerson.leave': 'Leave first person',
  'wall.prophecy.firstLine': 'The prophecy shall come true: one day a cherry pie will finish',
  'wall.prophecy.secondLine': 'this tea room, and it will live a life of its own. Or not.',
  'guide.title': 'How it works',
  'guide.taking.title': 'Taking things',
  'guide.taking.text': 'Tap a thing on a table, the counter or the shelf to take it. It goes into a free hand and becomes active, so you see a soft glow around it. The hand stays active even when you walk away. Tap it again to let go. You can choose a hand while you stand at a table, the counter or the shelf, or in first person.',
  'guide.pouring.title': 'Pouring',
  'guide.pouring.text': 'Choose what you pour from: the kettle, the thermos or a bowl. Tap the neck or the lid of what you pour into. Drag your vessel until its spout is over the other one, and hold the pour button in the bottom right corner to tilt it. Let go to stop the stream. Tap anywhere else when you are done.',
  'guide.looking.title': 'Looking closely',
  'guide.looking.text': 'Hold a finger or the mouse button for a second on a thing in your hand. It comes up close, and you can turn it and zoom in. Tap outside it to put it back.',
  'guide.washing.title': 'Washing a bowl',
  'guide.washing.text': 'Put the bowl in the sink and run the tap until the water spills over its rim. When you take the bowl out, the water is poured away.',
  'guide.previous': '‹',
  'guide.next': '›',
  'guide.pageNumber': '{page} of {pages}',
  'guide.close': 'Close',
  'achievements.title': 'Achievements',
  'achievements.reset': 'Reset',
  'achievements.resetAgain': 'Tap again to reset',
  'achievements.close': 'Close',
  'achievement.unlocked': '🏅 {title}',
  'achievement.burntClothWashed.title': 'Phoenix',
  'achievement.burntClothWashed.done': 'Set the cloth on fire, then washed it back to new.',
  'achievement.spoonBurnt.title': 'Yeah, fuck me',
  'achievement.spoonBurnt.done': 'Burnt the spoon until it crumbled to ash in your hand.',
  'achievement.bowlTriedOnTheHeater.title': 'History Lesson',
  'achievement.bowlTriedOnTheHeater.done': 'Tried to put a tea bowl on the heater and heard why not.',
  'achievement.everythingOnTheShelf.title': 'DVD',
  'achievement.everythingOnTheShelf.done': 'Everything fit on the shelf. Perfectly. Not one thing left over.',
  'achievement.tableWiped.title': 'OCD',
  'achievement.tableWiped.done': 'Wiped two different puddles with the cloth.',
  'achievement.thermosGlowing.title': 'Hanami',
  'achievement.thermosGlowing.done': 'Sat by the heater and watched the thermos blossom red-hot.',
  'achievement.heaterTester.title': 'Hopeless',
  'achievement.heaterTester.done': 'Tried four or five different things on the working heater.',
  'achievement.roseBushTappedTenTimes.title': 'The Shawshank Redemption',
  'achievement.roseBushTappedTenTimes.done': 'Tapped the rose bush ten times in a row.',
  'achievement.perfectTea.title': 'Sommelier',
  'achievement.perfectTea.done': 'Brewed a bowl of tea that was just right.',
  'achievement.teaBrewedInTheBowl.title': 'Enlightened',
  'achievement.teaBrewedInTheBowl.done': 'Skipped the kettle, brewed the leaves right in a tea bowl and drank it.',
  'achievement.visitContinued.title': 'The Usual, Please',
  'achievement.visitContinued.done': 'Came back and continued a visit.',
  'achievement.tapAndHeaterLeftOn.title': "Parents Wouldn't Approve",
  'achievement.tapAndHeaterLeftOn.done': 'Ran the tap into an empty sink for two minutes and the heater without the kettle for two minutes, then turned both off.',
  'achievement.kettleBoiledDry.title': 'Patience of a Monk',
  'achievement.kettleBoiledDry.done': 'Filled the kettle to the brim, poured nothing from it, and waited on the heater until it boiled dry.',
  'achievement.shiva.title': 'Shiva',
  'achievement.died.title': "You know, I'm something of an enthusiast myself",
  'achievement.died.done': 'Your little heart could not take a brew that strong.',
  'achievement.delphicOracle.title': 'Delphic Oracle',
  'achievement.delphicOracle.done': 'Found the prophecy where nobody looks, and read it whole.',
  'achievement.gourmet.title': 'Gourmet',
  'achievement.gourmet.done': 'Blended three different teas in one vessel.',
  'achievement.shiva.done': 'Wanted a third arm so badly that you tapped one into being. So proud of you.',

  'offering.glow': '{figurine} glows softly.',
  'offering.subtle': '{figurine} seems pleased.',
  'offering.barely': '{figurine} barely notices.',
  'figurine.dragon': 'The dragon',
  'figurine.toad': 'The toad',
} as const

export const englishPhrases = {
  'sip.noTea': [
    'Hmm… no smell of tea in here at all.',
    'Just water. The leaves never met it.',
    'Clear as the tap. Tea was meant to happen here.',
    'Water, honest and plain. The tea is still in the caddy.',
  ],
  'sip.tooHot': [
    'Mm, a touch too hot. Give it a moment.',
    'Hot on the lips. A few breaths and it will be lovely.',
    'Still a little fierce. Almost there.',
    'Ooh, hot. I rushed that one.',
  ],
  'sip.amongLeaves': [
    'Tea with a side of leaves. I am chewing my ceremony.',
    'The kettle is sulking over there. It thought we were friends.',
    'A leaf is stuck to my lip. Very rustic. Very wet.',
  ],
  'sip.overbrewed': [
    'Oof… it has gone bitter. It steeped too long.',
    'That bites back. Too long with the leaves.',
    'Dark and harsh. The leaves forgot to leave.',
    'Bitter all the way down. Too long in the kettle.',
  ],
  'sip.extremelyStrong': [
    'I can hear colours now. Is that part of the ceremony?',
    'A spoon would stand up in this. Respect.',
    'Only a true lover of strong tea survives this. I think I did.',
  ],
  'sip.bitter': [
    'A bitter edge. A little less time next pour.',
    'A touch sharp at the end.',
    'Good, then a bitter whisper.',
    'Almost. A shade too long.',
  ],
  'sip.tooStrong': [
    'Strong… it grips the tongue.',
    'Heavy. Fewer leaves next time.',
    'That wakes you up. Maybe too much.',
    'Thick as a winter coat.',
  ],
  'sip.cold': [
    'Cold already. The moment has passed.',
    'It waited too long for me.',
    'Cold tea, quiet regret.',
    'The warmth has gone somewhere else.',
  ],
  'sip.weak': [
    'Pale and thin. It wanted more leaves, or more time.',
    'Shy tea. Barely there.',
    'Mostly water, a rumour of tea.',
    'Gentle… too gentle.',
  ],
  'sip.rich': [
    'Rich and deep. Lovely.',
    'Full and round. Oh, that is good.',
    'Deep as the evening, and just as calm.',
    'Rich enough to lean on.',
  ],
  'sip.coolingButGood': [
    'Good, though it is cooling.',
    'Still good. Drink it before it goes.',
    'Nice, a little shy of warm.',
    'Cooler now, but still lovely.',
  ],
  'sip.justRight': [
    'Ahh… just right.',
    'Mm. Exactly this.',
    'That is the one.',
    'Warm, clear, kind. I could sit with this all day.',
  ],
  'spill': [
    'Oops… some for the table.',
    'The table wanted a sip too.',
    "Oh no, a puddle. Where's the cloth?",
    'Well, that went everywhere.',
  ],
  'sillIsTheRoomsOwn': [
    'Wow, you tap everything here. The room would like to keep something for itself.',
    'The figurines on the windowsill belong to the room. Admire them from here.',
    'You have touched almost everything in this house. These two are off the list.',
    'Not these ones. Some things in a house are only for looking at.',
  ],
  'bowlKeptOffTheHeater': [
    'Have you lost your mind? That bowl is the dearest thing in this house. Put your own hand there instead.',
    'The Guild of Beautiful Bowls has received a complaint about us. It is not amused.',
    'A potter shaped this bowl five centuries ago. They would never forgive us.',
    'A bowl on a hot plate? The bowl says no. I say no. Even the plate looks worried.',
  ],
  'caddyKeptOffTheHeater': [
    'If these were coffee beans, maybe. This tea was roasted long ago and is ready to drink. Shoo.',
    'The leaves are dry enough, thank you. Nobody ordered tea toast.',
    'Charcoal is not a tea. These leaves would like to stay leaves.',
    'The caddy has lived a quiet life on the shelf. It does not need a sauna.',
  ],
  'caddyWashedOut': [
    'Lovely. And what exactly are we drinking now? The view?',
    'The next tea delivery is a week away. Enjoy your hot water until then.',
    'Oh, I see. Off you go to your coffee, then.',
    'All of it, down the drain. Is tea some kind of joke to you?',
  ],
  'spoonReturned': [
    'The spoon is back in its old place. Bamboo grows fast, apparently.',
    'There is a spoon again. It knows nothing about the last one, and let us keep it that way.',
    'Someone swept up the ash and left a new spoon in its place. I will not ask who.',
    'A new spoon is waiting where the old one lay. Let us not introduce it to the heater.',
  ],
  'emptyCaddyRefilled': [
    'Fresh leaves in the caddy. Try to drink these ones.',
    'The caddy is full again. Will the leaves make it to the kettle this time?',
    'Someone filled the caddy while we were away.',
    'The delivery came early. The caddy is full, and the sink is not invited.',
  ],
  'spoonAndCaddyReturned': [
    'A new spoon and a full caddy. Let us try not to burn one or rinse the other.',
    'The spoon is back and the caddy is full. The house forgives more than it should.',
    'Fresh leaves, a fresh spoon. Everything is ready for you to ruin it again.',
    'While we were away, the spoon grew back and the caddy filled up. I have questions, but I will keep them to myself.',
  ],
  'lastWords': [
    'Tell the kettle… it was not its fault.',
    'The whole caddy… at once… worth it.',
    'Too strong. Tell the caddy I forgive it.',
  ],
  'obituary': [
    'Here lies a tea lover who brewed the whole caddy at once and drank it straight from the tin. Survived by ten tea bowls and a thermos.',
    'In loving memory. Cherished by the dragon and the toad, undone by a single caddy of tea.',
    'Gone today, strong to the end, like their tea. In lieu of flowers, please send a smaller caddy.',
    'Here rests one who wanted a stronger cup. They got one.',
  ],
  'handsFull': [
    'A third arm would help right now. Evolution is taking its time.',
    'Telekinesis is still on my list. Put something down first.',
    'Sorry, hands full. Unless you want me to carry it in my teeth.',
  ],
  'handsFullOfBowls': [
    'Waiters carry four bowls in one hand. I should practise that some quiet evening.',
    'Two bowls, two hands. Stacking them in one hand is a skill for another day.',
    'One day I will balance three bowls on one palm. Today is not that day.',
    'A real tea master holds two bowls in one hand. I will train when no one is watching.',
  ],
  'heaterTester': [
    'Everything goes on the heater, I see. Looks like we have caught ourselves a tester.',
    "Mummy's little arsonist is at it again.",
    'Is this really what you came to this game for? I may have to report some worrying behaviour.',
    'Who would have thought this would become the most popular feature of the tea room.',
    'This is exactly the behaviour I expected from you.',
    'We are renaming ourselves Fire Room. Or The Fireplace. Send in your suggestions.',
  ],
  'everythingOnTheShelf': [
    'Everything on the shelf. This house has never been so tidy.',
    'Every last thing put away. Is this a hobby, or should I be a little worried?',
    'All on the shelf. Are you quite sure they are in the right order?',
    'Very neat. Had it been up to me, I would have arranged it all quite differently.',
  ],
  'burntClothWashed': [
    "Amazing. A burnt cloth washes back to new. I think I'll stay in this world.",
    'Not a trace of the fire. This world forgives things. I could live here.',
    "Magic sink! The burn is gone. I'm never leaving.",
    'Burnt, rinsed, reborn. What a kind little world.',
  ],
  'smoulderingClothTaken': [
    'Careful with that. I never did get round to insuring this house.',
    'We have only just moved in. Let us keep the walls a little longer.',
    'Lovely. The last mortgage payment went out yesterday, and now this.',
    'Sure, let it burn. We will just buy another house, as we always do.',
  ],
  'spoonCrumbled': [
    'And there goes our only spoon. No spoon, no leaves. Hot water it is, then.',
    'Ash. That was bamboo a minute ago. Lovely trick. Now make it come back.',
    'Well, that settles the tea for today. Unless you work out how to brew without a spoon. There might be a way.',
    'Poor little spoon. It scooped so faithfully, and now it is a pinch of ash. 😭',
  ],
  'tooHotToHold': [
    'And then what? Juggle a glowing thermos?',
    "Blister my palm and ruin a lovely day? I'll pass, thanks.",
    "It's literally glowing. Even the thermos is telling you no.",
  ],
  'tapRanLong': [
    '{litres} litres straight down the drain. The river sends its thanks.',
    'That was {litres} litres for the sink. It has never been this hydrated.',
  ],
  'heaterRanLong': [
    'That much electricity would have bought a whole tin of good tea. Ah well, the air is warm.',
    'Promise me you do this before we leave the house, too.',
    '{kilowattHours} kWh to warm the air. The power plant sends its warmest regards.',
  ],
} as const satisfies Readonly<Record<string, Lines>>
