export type { Catalog } from './Definitions/Catalog.ts'
export { definitionIn } from '../Engine/Catalog.ts'
export type { RoomDefinition, Spot } from './Definitions/RoomDefinition.ts'
export type { VesselDefinition } from './Definitions/VesselDefinition.ts'
export { isHeating, isTheHeaterInUse, isTheThermostatWorking } from './Judgement/HeaterModes.ts'
export { blendOf, extremeStrengthFrom, judgeTaste, type TasteVerdict, type TeaInABlend } from './Judgement/TasteJudgement.ts'
export { hoursSinceSunriseOf } from './Judgement/TimeOfDayJudgement.ts'
export { totalLeafGrams } from './Chemistry/Brewing.ts'
export { howAClothChars, howTheSpoonChars } from './Chemistry/Charring.ts'
export { clampedToShare } from '../Engine/ClampedToShare.ts'
export { willGrowTooHotToHoldWithin } from './Chemistry/Heat.ts'
export { isEmpty, shareOfTheStrengthByTeaId, type Liquid } from './Chemistry/Liquid.ts'
export { tiltWhereTheStreamSplashes, tiltWhereWaterStartsDegrees } from './Chemistry/Pouring.ts'
export type { Command } from './Simulation/Command.ts'
export { itemKindOf } from './Simulation/ItemKinds.ts'
export { puddleIdUnder, sameTopWithinMetres, wetMlAt } from './Simulation/Puddles.ts'
export { puddleRadiusMetres, shareOfWhatTheClothHolds } from './Chemistry/Table.ts'
export type { TeaEvent } from './Simulation/TeaEvent.ts'
export type { LogLine } from '../Engine/Log.ts'
export { TeaSession, type WouldBeRefused } from './Simulation/TeaSession.ts'
export type { DeepReadonly } from '../Engine/DeepReadonly.ts'
export { sessionStateVersion } from './State/FittedSavedState.ts'
export { isThePourRunningOverItsTarget, isThePourStreamRunning } from './State/PourStream.ts'
export type { ClothState, HandIndex, InventorySlot, ItemLocation, PourState, SessionState, TapUse, VesselState } from './State/SessionState.ts'
export { carriedItemIdsIn, isACloth, itemIdInHand, itemIdInTheInventory, itemIdInTheSink, itemIdOnTheHeater, itemIdsInTheHands, itemIdsInTheInventory, itemLocationIn, spoonItemId, standingSpotOf } from './State/WhereItemsAre.ts'
